/*
 * 10x: Database
 * 20x: Web API
 */
module.exports = {
	101: 'INVALID QUERY',
	102: 'INVALID PRIMARY KEY TYPE',
	103: 'INVALID DATA',
	104: 'UNDEFINED PRIMARY KEY',

	201: 'EMAIL NOT FOUND',
	202: 'EMAIL AND PASSWORD DO NOT MATCH',
	203: 'INVALID DATA',
	204: 'BANISHED USER'
}